# Generated by Django 5.2 on 2025-05-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userparticipant_first_entry_at'),
        ('forms', '0003_formresponse_formfieldresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('file', models.FileField(upload_to='videos/', verbose_name='Видеофайл')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(verbose_name='Время паузы в секундах')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='accounts.userparticipant')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='videos.video')),
            ],
        ),
    ]
