# Generated by Django 5.2 on 2025-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopause',
            name='frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='Основная частота (Hz)'),
        ),
    ]
