# Generated by Django 5.2 on 2025-05-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videopause_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A', 'До 5 дня'), ('B', 'С 6 по 30 день')], max_length=1)),
                ('min_timestamp', models.FloatField(verbose_name='Минимальное значение таймкода (сек)')),
                ('max_timestamp', models.FloatField(verbose_name='Максимальное значение таймкода (сек)')),
                ('file', models.FileField(upload_to='exercises/', verbose_name='Видео упражнения')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
    ]
