# Generated by Django 5.2 on 2025-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userparticipant_email_userparticipant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparticipant',
            name='first_entry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
