# Generated by Django 5.2 on 2025-05-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userparticipant_first_entry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparticipant',
            name='study_days',
            field=models.PositiveIntegerField(choices=[(15, '15 дней'), (30, '30 дней')], default=30),
        ),
    ]
