# Generated by Django 5.2.5 on 2025-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='exersice_timecode',
            new_name='exercise_timecode',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='consent_agreed',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
