# Generated by Django 5.2.5 on 2025-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_input_placeholder"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="section",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="test",
            name="scores_by_section",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="test",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="test",
            unique_together={("participant", "day")},
        ),
    ]
