# Generated by Django 5.2.5 on 2025-08-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_fill_sections_and_native_ids"),
    ]

    operations = []
