# Generated by Django 5.2.5 on 2025-08-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_question_number_and_update_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number', 'id']},
        ),
    ]
