# Generated by Django 5.2.5 on 2025-08-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_calming_video_segment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["number", "id"]},
        ),
    ]
