# Generated by Django 5.2 on 2025-08-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_question_options'),
        ('core', '0014_alter_question_options'),
    ]

    operations = [
    ]
