# Generated by Django 5.2 on 2025-08-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20250820_1036'),
        ('core', '0018_reset_questions_hard_seed'),
    ]

    operations = [
    ]
