# Generated by Django 5.2 on 2025-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20250820_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
