# Generated by Django 5.2.5 on 2025-08-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_participant_is_tg_auth_participant_is_vk_auth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmailRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.participant')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('participant', 'date')},
            },
        ),
    ]
