# Generated by Django 5.2 on 2025-05-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название формы')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Надпись')),
                ('field_type', models.CharField(choices=[('text', 'Текстовое поле'), ('textarea', 'Многострочный текст'), ('select', 'Выпадающий список'), ('checkbox', 'Чекбокс')], max_length=20, verbose_name='Тип поля')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('options', models.TextField(blank=True, help_text='Через запятую: вариант 1, вариант 2, ...', verbose_name='Опции (для select)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
