# Generated by Django 5.2 on 2025-05-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текстовое поле'), ('textarea', 'Многострочный текст'), ('select', 'Выпадающий список'), ('checkbox', 'Флажки (множественный выбор)'), ('radio', 'Радиокнопки (одиночный выбор)')], max_length=20, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.TextField(blank=True, help_text='Через запятую: вариант 1, вариант 2, ...', verbose_name='Опции (для select / checkbox / radio)'),
        ),
    ]
