# Generated by Django 5.2 on 2025-05-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formresponse_formfieldresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название группы форм')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='forms.formgroup'),
        ),
    ]
