# Generated by Django 5.2 on 2025-05-05 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userparticipant_first_entry_at'),
        ('forms', '0004_formgroup_form_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormGroupExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userparticipant')),
            ],
        ),
    ]
